### ISSUE TITLE
Installing from OJS plugin gallery appears broken

### ISSUE THREAD

**Issue by otuoma** [ojsde/lucene#13]
I am installing this plugin on OJS 3.2.1.3 using the plugin gallery page and it displays the following  and does not install the plugin itself

![Screenshot 2021-07-10 at 18-57-10 Website Settings](https://user-images.githubusercontent.com/12611023/125169177-a34b1580-e1b1-11eb-9512-932b17b41060.png)

I am on Ubuntu 20.04 with openjdk-8-jdk and php7.4

**Comment by asmecher** [comment]
@otuoma, do you receive an error message of some kind? Is there anything relevant in the PHP error log?

**Comment by lucascarrizo72818** [comment]
Hi @asmecher I am experimenting the same problem. Here is the message I recieved: 
![lucene](https://user-images.githubusercontent.com/42209213/130961841-464244f1-64bb-433e-96f5-62f3e4486ef1.png)
It is strange because I am able to install any other plugin from the plugin gallery. Any advice will be awesome

**Comment by asmecher** [comment]
@lucascarrizo72818, what version of OJS are you using?

**Comment by lucascarrizo72818** [comment]
@asmecher thanks for the response. I am using 3.2.1.2

**Comment by asmecher** [comment]
@lucascarrizo72818, I'm not sure this is the same issue, but I'd suggest looking at the file permissions in your PHP `sys_get_temp_dir()` and the subdirectory there that OJS tried to extract the plugin into. One of the last steps in plugin installation is to remove that directory (after the plugin has been put in place in the OJS installation), and it looks like it's not allowed to do that. See: https://github.com/pkp/pkp-lib/blob/stable-3_2_1/classes/plugins/PluginHelper.inc.php#L116

**Comment by asmecher** [comment]
Closing as out of date.
