### ISSUE TITLE
[OJS 3.2.1.4] Error in Scheduled Tasks an not show metrics

### ISSUE THREAD

**Issue by diegomejia071** [ojsde/lucene#19]
Hi,

I have had an error for almost a month since the Usage Stats are not shown and remain in the stage phase.

![image](https://user-images.githubusercontent.com/21009904/174838150-f786292c-cabb-4a74-8332-325490933ca2.png)

I have the Acron plugin enabled and also when I try to run php tools/runScheduledTasks.php plugins/generic/usageStats/scheduledTasks.xml, after a while, it shows me the following error:

`PHP Fatal error:  Uncaught Error: Call to a member function getData() on null in /lib/pkp/classes/submission/Representation.inc.php:134
Stack trace:
#0 /lib/pkp/classes/statistics/PKPMetricsDAO.inc.php(378): Representation->getContextId()
#1 /classes/statistics/MetricsDAO.inc.php(47): PKPMetricsDAO->foreignKeyLookup(515, 246408)
#2 /lib/pkp/classes/statistics/PKPMetricsDAO.inc.php(284): MetricsDAO->foreignKeyLookup(515, 246408)
#3 /plugins/generic/usageStats/UsageStatsLoader.inc.php(823): PKPMetricsDAO->insertRecord(Array)
#4 /plugins/generic/usageStats/UsageStatsLoader.inc.php(228): UsageStatsLoader->_loadData('usage_events_20...')
#5 /lib/pkp/classes/task/FileLoader.inc.php(167): UsageStatsLoader->processFile('/datos/usageSta...')
#6 /lib/pkp/classes/submission/Representation.inc.php on line 134
`

**Comment by ronste** [comment]
Hi @diegomejia071 ,

I think you posted to the wrong repo. Your question and errors are related to the PKP usageStats plugin. This repo is about the Lucene plugin.
