### ISSUE TITLE
Support for newer OJS (3.2 or 3.3)

### ISSUE THREAD

**Issue by rissajeanne** [ojsde/lucene#7]
Hi, do you have plans to update this plugin for the latest stable release of OJS?

**Comment by CFanselow** [comment]
Hi @rissajeanne, 

we'll discuss it and reply to you asap.

**Comment by CFanselow** [comment]
Hi @rissajeanne, 

we decided not to update the plugin, but see https://github.com/ojsde/lucene/issues/6.

**Comment by withanage** [comment]
@rissajeanne  the plugin was ported to OJS  3.2 plugin gallery yesterday.
